// <autogenerated>
//   This file was generated by T4 code generator AllBusinessModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using TrackableEntities.Client;


		namespace AllocationDS.Business.Entities
{
    public partial class XSales_UnAllocated
    {
       
         partial void TrackableStartUp()
         {
           // _changeTracker = new ChangeTrackingCollection<XSales_UnAllocated>(this);
         }

        ChangeTrackingCollection<XSales_UnAllocated> _changeTracker;

        [NotMapped]
        [IgnoreDataMember]
        public ChangeTrackingCollection<XSales_UnAllocated> ChangeTracker
        {
            get
            {
                return _changeTracker;
            }
        }

         public void StartTracking()
        {
            _changeTracker = new ChangeTrackingCollection<XSales_UnAllocated>(this);
        }
   
    }
}
		