// <autogenerated>
//   This file was generated by T4 code generator AllDataSpaceViewModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.Threading.Tasks;
//using SimpleMvvmToolkit;
using DocumentDS.Business.Entities;
using DocumentDS.Business.Services;




namespace WaterNut.DataSpace.DocumentDS.DataModels
{
	public partial class Document_TypeDataModel_AutoGen 
	{
        private static readonly Document_TypeDataModel_AutoGen instance;
        static Document_TypeDataModel_AutoGen()
        {
            instance = new Document_TypeDataModel_AutoGen();
        }

        public static  Document_TypeDataModel_AutoGen Instance
        {
            get { return instance; }
        }

       //Search Entities 
        public async Task<IEnumerable<Document_Type>> SearchDocument_Type(List<string> lst, List<string> includeLst = null )
        {
            using (var ctx = new Document_TypeService())
            {
                return await ctx.GetDocument_TypeByExpressionLst(lst, includeLst).ConfigureAwait(false);
            }
        }

    }
}
		
