//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuationDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered : xC71_Value_declaration_form
    {
        public string id { get; set; }
        public string RegNumber { get; set; }
        public string SourceFile { get; set; }
        public string DocumentReference { get; set; }
        public int ApplicationSettingsId { get; set; }
    }
}
