//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterNutDB
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class xcuda_Means_of_transport
    {
        public xcuda_Means_of_transport()
        {
            this.xcuda_Border_information = new HashSet<xcuda_Border_information>();
            this.xcuda_Departure_arrival_information = new HashSet<xcuda_Departure_arrival_information>();
        }
    
        public int Means_of_transport_Id { get; set; }
        public Nullable<int> Transport_Id { get; set; }
        public string Inland_mode_of_transport { get; set; }
    
        public virtual ICollection<xcuda_Border_information> xcuda_Border_information { get; set; }
        public virtual ICollection<xcuda_Departure_arrival_information> xcuda_Departure_arrival_information { get; set; }
        public virtual xcuda_Transport xcuda_Transport { get; set; }
    }
}
