// <autogenerated>
//   This file was generated by T4 code generator AllRepository.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Core.Common.Client.Services;
using Core.Common.Client.Repositories;
using OCR.Client.Services;
using OCR.Client.Entities;
using OCR.Client.DTO;
using Core.Common.Business.Services;
using System.Diagnostics;


using System.Threading.Tasks;
using System.Linq;
using Core.Common;
using System.ComponentModel;
using System.Collections.Generic;
using System;
using System.ServiceModel;
using TrackableEntities.Common;

using vw_OCRCorrectionAnalysis = OCR.Client.Entities.vw_OCRCorrectionAnalysis;

namespace OCR.Client.Repositories 
{
   
    public partial class vw_OCRCorrectionAnalysisRepository : BaseRepository<vw_OCRCorrectionAnalysisRepository>
    {

       private static readonly vw_OCRCorrectionAnalysisRepository instance;
       static vw_OCRCorrectionAnalysisRepository()
        {
            instance = new vw_OCRCorrectionAnalysisRepository();
        }

       public static vw_OCRCorrectionAnalysisRepository Instance
        {
            get { return instance; }
        }
        
        public async Task<IEnumerable<vw_OCRCorrectionAnalysis>> vw_OCRCorrectionAnalysis(List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return new List<vw_OCRCorrectionAnalysis>().AsEnumerable();
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
                        var res = await t.Getvw_OCRCorrectionAnalysis(includesLst).ConfigureAwait(continueOnCapturedContext: false);
                        if (res != null)
                        {
                            return res.Select(x => new vw_OCRCorrectionAnalysis(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<vw_OCRCorrectionAnalysis>> Getvw_OCRCorrectionAnalysisByExpression(string exp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<vw_OCRCorrectionAnalysis>().AsEnumerable();
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
					    IEnumerable<DTO.vw_OCRCorrectionAnalysis> res = null;
                        if(exp == "All")
                        {                       
						    res = await t.Getvw_OCRCorrectionAnalysis(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.Getvw_OCRCorrectionAnalysisByExpression(exp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new vw_OCRCorrectionAnalysis(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<vw_OCRCorrectionAnalysis>> Getvw_OCRCorrectionAnalysisByExpressionLst(List<string> expLst, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || expLst.Count == 0 || expLst.FirstOrDefault() == "None") return new List<vw_OCRCorrectionAnalysis>().AsEnumerable();
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
					    IEnumerable<DTO.vw_OCRCorrectionAnalysis> res = null;
                       
                        res = await t.Getvw_OCRCorrectionAnalysisByExpressionLst(expLst, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                      
                    
                        if (res != null)
                        {
                            return res.Select(x => new vw_OCRCorrectionAnalysis(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


		 public async Task<IEnumerable<vw_OCRCorrectionAnalysis>> Getvw_OCRCorrectionAnalysisByExpressionNav(string exp, Dictionary<string, string> navExp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<vw_OCRCorrectionAnalysis>().AsEnumerable();
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
					    IEnumerable<DTO.vw_OCRCorrectionAnalysis> res = null;
                        if(exp == "All" && navExp.Count == 0)
                        {                       
						    res = await t.Getvw_OCRCorrectionAnalysis(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.Getvw_OCRCorrectionAnalysisByExpressionNav(exp, navExp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new vw_OCRCorrectionAnalysis(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


        public async Task<vw_OCRCorrectionAnalysis> Getvw_OCRCorrectionAnalysis(string id, List<string> includesLst = null)
        {
             try
             {   
                 using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
                        var res = await t.Getvw_OCRCorrectionAnalysisByKey(id,includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return new vw_OCRCorrectionAnalysis(res);
                    }
                    else
                    {
                        return null;
                    }                    
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<vw_OCRCorrectionAnalysis> Updatevw_OCRCorrectionAnalysis(vw_OCRCorrectionAnalysis entity)
        {
            if (entity == null) return entity;
            var entitychanges = entity.ChangeTracker.GetChanges().FirstOrDefault();
            if (entitychanges != null)
            {
                try
                {
                    using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
     
                        var updatedEntity =  await t.Updatevw_OCRCorrectionAnalysis(entitychanges).ConfigureAwait(false);
                        entity.EntityId = updatedEntity.EntityId;
                        entity.DTO.AcceptChanges();
                         //var  = entity.;
                        //entity.ChangeTracker.MergeChanges(,updatedEntity);
                        //entity. = ;
                        return entity;
                    }
                }
                catch (FaultException<ValidationFault> e)
                {
                    throw new Exception(e.Detail.Message, e.InnerException);
                }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
            }
            else
            {
                return entity;
            }

        }

        public async Task<vw_OCRCorrectionAnalysis> Createvw_OCRCorrectionAnalysis(vw_OCRCorrectionAnalysis entity)
        {
            try
            {   
                using (var t = new vw_OCRCorrectionAnalysisClient())
                    {
                        return new vw_OCRCorrectionAnalysis(await t.Createvw_OCRCorrectionAnalysis(entity.DTO).ConfigureAwait(continueOnCapturedContext: false));
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<bool> Deletevw_OCRCorrectionAnalysis(string id)
        {
            try
            {
             using (var t = new vw_OCRCorrectionAnalysisClient())
                {
                    return await t.Deletevw_OCRCorrectionAnalysis(id).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }         
        }

        public async Task<bool> RemoveSelectedvw_OCRCorrectionAnalysis(IEnumerable<string> selectedvw_OCRCorrectionAnalysis)
        {
            try
            {
                using (var ctx = new vw_OCRCorrectionAnalysisClient())
                {
                    return await ctx.RemoveSelectedvw_OCRCorrectionAnalysis(selectedvw_OCRCorrectionAnalysis).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }      
        }


		//Virtural List Implementation

		public async Task<Tuple<IEnumerable<vw_OCRCorrectionAnalysis>, int>> LoadRange(int startIndex, int count, string exp, Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
        {
			var overallCount = 0;
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None")
            {
                
                return new Tuple<IEnumerable<vw_OCRCorrectionAnalysis>, int>(new List<vw_OCRCorrectionAnalysis>().AsEnumerable(), overallCount);
            }
            
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                {

                    IEnumerable<DTO.vw_OCRCorrectionAnalysis> res = null;
                                         
						    res = await t.LoadRangeNav(startIndex, count, exp, navExp, includeLst).ConfigureAwait(continueOnCapturedContext: false);
						    overallCount = await t.CountNav(exp, navExp).ConfigureAwait(continueOnCapturedContext: false);
                   
                   
                                
                    if (res != null)
                    {
                        return new Tuple<IEnumerable<vw_OCRCorrectionAnalysis>, int>(res.Select(x => new vw_OCRCorrectionAnalysis(x)).AsEnumerable(), overallCount);
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        
		public decimal SumField(string whereExp, string sumExp)
        {
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                {
                    return t.SumField(whereExp,sumExp);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }

        public async Task<decimal> SumNav(string whereExp, Dictionary<string, string> navExp, string sumExp)
        {
            try
            {
                using (var t = new vw_OCRCorrectionAnalysisClient())
                {
                    return await t.SumNav(whereExp,navExp,sumExp).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }
    }
}

