// <autogenerated>
//   This file was generated by T4 code generator AllRepository.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Core.Common.Client.Services;
using Core.Common.Client.Repositories;
using CoreEntities.Client.Services;
using CoreEntities.Client.Entities;
using CoreEntities.Client.DTO;
using Core.Common.Business.Services;
using System.Diagnostics;


using System.Threading.Tasks;
using System.Linq;
using Core.Common;
using System.ComponentModel;
using System.Collections.Generic;
using System;
using System.ServiceModel;
using TrackableEntities.Common;

using TODO_ERRReport_UnmappedItems = CoreEntities.Client.Entities.TODO_ERRReport_UnmappedItems;

namespace CoreEntities.Client.Repositories 
{
   
    public partial class TODO_ERRReport_UnmappedItemsRepository : BaseRepository<TODO_ERRReport_UnmappedItemsRepository>
    {

       private static readonly TODO_ERRReport_UnmappedItemsRepository instance;
       static TODO_ERRReport_UnmappedItemsRepository()
        {
            instance = new TODO_ERRReport_UnmappedItemsRepository();
        }

       public static TODO_ERRReport_UnmappedItemsRepository Instance
        {
            get { return instance; }
        }
        
        public async Task<IEnumerable<TODO_ERRReport_UnmappedItems>> TODO_ERRReport_UnmappedItems(List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return new List<TODO_ERRReport_UnmappedItems>().AsEnumerable();
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
                        var res = await t.GetTODO_ERRReport_UnmappedItems(includesLst).ConfigureAwait(continueOnCapturedContext: false);
                        if (res != null)
                        {
                            return res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpression(string exp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<TODO_ERRReport_UnmappedItems>().AsEnumerable();
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
					    IEnumerable<DTO.TODO_ERRReport_UnmappedItems> res = null;
                        if(exp == "All")
                        {                       
						    res = await t.GetTODO_ERRReport_UnmappedItems(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.GetTODO_ERRReport_UnmappedItemsByExpression(exp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpressionLst(List<string> expLst, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || expLst.Count == 0 || expLst.FirstOrDefault() == "None") return new List<TODO_ERRReport_UnmappedItems>().AsEnumerable();
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
					    IEnumerable<DTO.TODO_ERRReport_UnmappedItems> res = null;
                       
                        res = await t.GetTODO_ERRReport_UnmappedItemsByExpressionLst(expLst, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                      
                    
                        if (res != null)
                        {
                            return res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


		 public async Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpressionNav(string exp, Dictionary<string, string> navExp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<TODO_ERRReport_UnmappedItems>().AsEnumerable();
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
					    IEnumerable<DTO.TODO_ERRReport_UnmappedItems> res = null;
                        if(exp == "All" && navExp.Count == 0)
                        {                       
						    res = await t.GetTODO_ERRReport_UnmappedItems(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.GetTODO_ERRReport_UnmappedItemsByExpressionNav(exp, navExp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


        public async Task<TODO_ERRReport_UnmappedItems> GetTODO_ERRReport_UnmappedItems(string id, List<string> includesLst = null)
        {
             try
             {   
                 using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
                        var res = await t.GetTODO_ERRReport_UnmappedItemsByKey(id,includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return new TODO_ERRReport_UnmappedItems(res);
                    }
                    else
                    {
                        return null;
                    }                    
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<TODO_ERRReport_UnmappedItems> UpdateTODO_ERRReport_UnmappedItems(TODO_ERRReport_UnmappedItems entity)
        {
            if (entity == null) return entity;
            var entitychanges = entity.ChangeTracker.GetChanges().FirstOrDefault();
            if (entitychanges != null)
            {
                try
                {
                    using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
     
                        var updatedEntity =  await t.UpdateTODO_ERRReport_UnmappedItems(entitychanges).ConfigureAwait(false);
                        entity.EntityId = updatedEntity.EntityId;
                        entity.DTO.AcceptChanges();
                         //var  = entity.;
                        //entity.ChangeTracker.MergeChanges(,updatedEntity);
                        //entity. = ;
                        return entity;
                    }
                }
                catch (FaultException<ValidationFault> e)
                {
                    throw new Exception(e.Detail.Message, e.InnerException);
                }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
            }
            else
            {
                return entity;
            }

        }

        public async Task<TODO_ERRReport_UnmappedItems> CreateTODO_ERRReport_UnmappedItems(TODO_ERRReport_UnmappedItems entity)
        {
            try
            {   
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                    {
                        return new TODO_ERRReport_UnmappedItems(await t.CreateTODO_ERRReport_UnmappedItems(entity.DTO).ConfigureAwait(continueOnCapturedContext: false));
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<bool> DeleteTODO_ERRReport_UnmappedItems(string id)
        {
            try
            {
             using (var t = new TODO_ERRReport_UnmappedItemsClient())
                {
                    return await t.DeleteTODO_ERRReport_UnmappedItems(id).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }         
        }

        public async Task<bool> RemoveSelectedTODO_ERRReport_UnmappedItems(IEnumerable<string> selectedTODO_ERRReport_UnmappedItems)
        {
            try
            {
                using (var ctx = new TODO_ERRReport_UnmappedItemsClient())
                {
                    return await ctx.RemoveSelectedTODO_ERRReport_UnmappedItems(selectedTODO_ERRReport_UnmappedItems).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }      
        }


		//Virtural List Implementation

		public async Task<Tuple<IEnumerable<TODO_ERRReport_UnmappedItems>, int>> LoadRange(int startIndex, int count, string exp, Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
        {
			var overallCount = 0;
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None")
            {
                
                return new Tuple<IEnumerable<TODO_ERRReport_UnmappedItems>, int>(new List<TODO_ERRReport_UnmappedItems>().AsEnumerable(), overallCount);
            }
            
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                {

                    IEnumerable<DTO.TODO_ERRReport_UnmappedItems> res = null;
                                         
						    res = await t.LoadRangeNav(startIndex, count, exp, navExp, includeLst).ConfigureAwait(continueOnCapturedContext: false);
						    overallCount = await t.CountNav(exp, navExp).ConfigureAwait(continueOnCapturedContext: false);
                   
                   
                                
                    if (res != null)
                    {
                        return new Tuple<IEnumerable<TODO_ERRReport_UnmappedItems>, int>(res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable(), overallCount);
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

	 public async Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByApplicationSettingsId(string ApplicationSettingsId, List<string> includesLst = null)
        {
             if (ApplicationSettingsId == "0") return null;
            try
            {
                 using (TODO_ERRReport_UnmappedItemsClient t = new TODO_ERRReport_UnmappedItemsClient())
                    {
                        var res = await t.GetTODO_ERRReport_UnmappedItemsByApplicationSettingsId(ApplicationSettingsId, includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return res.Select(x => new TODO_ERRReport_UnmappedItems(x)).AsEnumerable();
					    }                
					    else
					    {
						    return null;
					    }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        } 
         
		public decimal SumField(string whereExp, string sumExp)
        {
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                {
                    return t.SumField(whereExp,sumExp);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }

        public async Task<decimal> SumNav(string whereExp, Dictionary<string, string> navExp, string sumExp)
        {
            try
            {
                using (var t = new TODO_ERRReport_UnmappedItemsClient())
                {
                    return await t.SumNav(whereExp,navExp,sumExp).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }
    }
}

