// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using CoreEntities.Client.DTO;


namespace CoreEntities.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface ITODO_ERRReport_UnmappedItemsService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItems(List<string> includesLst = null);

        [OperationContract]
        Task<TODO_ERRReport_UnmappedItems> GetTODO_ERRReport_UnmappedItemsByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<TODO_ERRReport_UnmappedItems> UpdateTODO_ERRReport_UnmappedItems(TODO_ERRReport_UnmappedItems entity);

        [OperationContract]
        Task<TODO_ERRReport_UnmappedItems> CreateTODO_ERRReport_UnmappedItems(TODO_ERRReport_UnmappedItems entity);

        [OperationContract]
        Task<bool> DeleteTODO_ERRReport_UnmappedItems(string id);

        [OperationContract]
        Task<bool> RemoveSelectedTODO_ERRReport_UnmappedItems(IEnumerable<string> selectedTODO_ERRReport_UnmappedItems);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<TODO_ERRReport_UnmappedItems>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<TODO_ERRReport_UnmappedItems>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				[OperationContract]
		Task<IEnumerable<TODO_ERRReport_UnmappedItems>> GetTODO_ERRReport_UnmappedItemsByApplicationSettingsId(string ApplicationSettingsId, List<string> includesLst = null);
        
  		
    }
}

