// <autogenerated>
//   This file was generated by T4 code generator AllClientModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using CoreEntities.Client.Entities;
using CoreEntities.Client.Services;
//using WaterNut.Client.Services;
using CounterPointQS.Client.Services;

using System;

namespace CounterPointQS.Client.Entities
{
    public partial class CounterPointSales
    {
       
       #region IIdentifiable Entities
        public override string EntityId
        {
            get
            {
                return this.InvoiceNo.ToString();//this.InvoiceNo == null?"0":			
            }
            set
            {
                this.InvoiceNo = Convert.ToString(value);
            }
        }



         #endregion
    }
   
}
		