// <autogenerated>
//   This file was generated by T4 code generator AllRepository.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Core.Common.Client.Services;
using Core.Common.Client.Repositories;
using AdjustmentQS.Client.Services;
using AdjustmentQS.Client.Entities;
using AdjustmentQS.Client.DTO;
using Core.Common.Business.Services;
using System.Diagnostics;


using System.Threading.Tasks;
using System.Linq;
using Core.Common;
using System.ComponentModel;
using System.Collections.Generic;
using System;
using System.ServiceModel;
using TrackableEntities.Common;

using AsycudaDocumentEntryData = AdjustmentQS.Client.Entities.AsycudaDocumentEntryData;

namespace AdjustmentQS.Client.Repositories 
{
   
    public partial class AsycudaDocumentEntryDataRepository : BaseRepository<AsycudaDocumentEntryDataRepository>
    {

       private static readonly AsycudaDocumentEntryDataRepository instance;
       static AsycudaDocumentEntryDataRepository()
        {
            instance = new AsycudaDocumentEntryDataRepository();
        }

       public static AsycudaDocumentEntryDataRepository Instance
        {
            get { return instance; }
        }
        
        public async Task<IEnumerable<AsycudaDocumentEntryData>> AsycudaDocumentEntryDatas(List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return new List<AsycudaDocumentEntryData>().AsEnumerable();
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                    {
                        var res = await t.GetAsycudaDocumentEntryDatas(includesLst).ConfigureAwait(continueOnCapturedContext: false);
                        if (res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<AsycudaDocumentEntryData>> GetAsycudaDocumentEntryDatasByExpression(string exp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<AsycudaDocumentEntryData>().AsEnumerable();
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                    {
					    IEnumerable<DTO.AsycudaDocumentEntryData> res = null;
                        if(exp == "All")
                        {                       
						    res = await t.GetAsycudaDocumentEntryDatas(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.GetAsycudaDocumentEntryDatasByExpression(exp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

		 public async Task<IEnumerable<AsycudaDocumentEntryData>> GetAsycudaDocumentEntryDatasByExpressionLst(List<string> expLst, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || expLst.Count == 0 || expLst.FirstOrDefault() == "None") return new List<AsycudaDocumentEntryData>().AsEnumerable();
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                    {
					    IEnumerable<DTO.AsycudaDocumentEntryData> res = null;
                       
                        res = await t.GetAsycudaDocumentEntryDatasByExpressionLst(expLst, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                      
                    
                        if (res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


		 public async Task<IEnumerable<AsycudaDocumentEntryData>> GetAsycudaDocumentEntryDatasByExpressionNav(string exp, Dictionary<string, string> navExp, List<string> includesLst = null)
        {
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None") return new List<AsycudaDocumentEntryData>().AsEnumerable();
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                    {
					    IEnumerable<DTO.AsycudaDocumentEntryData> res = null;
                        if(exp == "All" && navExp.Count == 0)
                        {                       
						    res = await t.GetAsycudaDocumentEntryDatas(includesLst).ConfigureAwait(continueOnCapturedContext: false);					
                        }
                        else
                        {
                             res = await t.GetAsycudaDocumentEntryDatasByExpressionNav(exp, navExp, includesLst).ConfigureAwait(continueOnCapturedContext: false);	                         
                        }
                    
                        if (res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
                        }
                        else
                        {
                            return null;
                        }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }


        public async Task<AsycudaDocumentEntryData> GetAsycudaDocumentEntryData(string id, List<string> includesLst = null)
        {
             try
             {   
                 using (var t = new AsycudaDocumentEntryDataClient())
                    {
                        var res = await t.GetAsycudaDocumentEntryDataByKey(id,includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return new AsycudaDocumentEntryData(res)
                    {
                  // AdjustmentEx = (res.AdjustmentEx != null?new AdjustmentEx(res.AdjustmentEx): null)    
                  };
                    }
                    else
                    {
                        return null;
                    }                    
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<AsycudaDocumentEntryData> UpdateAsycudaDocumentEntryData(AsycudaDocumentEntryData entity)
        {
            if (entity == null) return entity;
            var entitychanges = entity.ChangeTracker.GetChanges().FirstOrDefault();
            if (entitychanges != null)
            {
                try
                {
                    using (var t = new AsycudaDocumentEntryDataClient())
                    {
     
                        var updatedEntity =  await t.UpdateAsycudaDocumentEntryData(entitychanges).ConfigureAwait(false);
                        entity.EntityId = updatedEntity.EntityId;
                        entity.DTO.AcceptChanges();
                         //var  = entity.;
                        //entity.ChangeTracker.MergeChanges(,updatedEntity);
                        //entity. = ;
                        return entity;
                    }
                }
                catch (FaultException<ValidationFault> e)
                {
                    throw new Exception(e.Detail.Message, e.InnerException);
                }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
            }
            else
            {
                return entity;
            }

        }

        public async Task<AsycudaDocumentEntryData> CreateAsycudaDocumentEntryData(AsycudaDocumentEntryData entity)
        {
            try
            {   
                using (var t = new AsycudaDocumentEntryDataClient())
                    {
                        return new AsycudaDocumentEntryData(await t.CreateAsycudaDocumentEntryData(entity.DTO).ConfigureAwait(continueOnCapturedContext: false));
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

        public async Task<bool> DeleteAsycudaDocumentEntryData(string id)
        {
            try
            {
             using (var t = new AsycudaDocumentEntryDataClient())
                {
                    return await t.DeleteAsycudaDocumentEntryData(id).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }         
        }

        public async Task<bool> RemoveSelectedAsycudaDocumentEntryData(IEnumerable<string> selectedAsycudaDocumentEntryData)
        {
            try
            {
                using (var ctx = new AsycudaDocumentEntryDataClient())
                {
                    return await ctx.RemoveSelectedAsycudaDocumentEntryData(selectedAsycudaDocumentEntryData).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }  
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }      
        }


		//Virtural List Implementation

		public async Task<Tuple<IEnumerable<AsycudaDocumentEntryData>, int>> LoadRange(int startIndex, int count, string exp, Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
        {
			var overallCount = 0;
            if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime || exp == null || exp == "None")
            {
                
                return new Tuple<IEnumerable<AsycudaDocumentEntryData>, int>(new List<AsycudaDocumentEntryData>().AsEnumerable(), overallCount);
            }
            
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                {

                    IEnumerable<DTO.AsycudaDocumentEntryData> res = null;
                                         
						    res = await t.LoadRangeNav(startIndex, count, exp, navExp, includeLst).ConfigureAwait(continueOnCapturedContext: false);
						    overallCount = await t.CountNav(exp, navExp).ConfigureAwait(continueOnCapturedContext: false);
                   
                   
                                
                    if (res != null)
                    {
                        return new Tuple<IEnumerable<AsycudaDocumentEntryData>, int>(res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable(), overallCount);
                    }
                    else
                    {
                        return null;
                    }
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        }

	 public async Task<IEnumerable<AsycudaDocumentEntryData>> GetAsycudaDocumentEntryDataByAsycudaDocumentId(string AsycudaDocumentId, List<string> includesLst = null)
        {
             if (AsycudaDocumentId == "0") return null;
            try
            {
                 using (AsycudaDocumentEntryDataClient t = new AsycudaDocumentEntryDataClient())
                    {
                        var res = await t.GetAsycudaDocumentEntryDataByAsycudaDocumentId(AsycudaDocumentId, includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
					    }                
					    else
					    {
						    return null;
					    }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        } 
 	 public async Task<IEnumerable<AsycudaDocumentEntryData>> GetAsycudaDocumentEntryDataByEntryDataId(string EntryDataId, List<string> includesLst = null)
        {
             if (EntryDataId == "0") return null;
            try
            {
                 using (AsycudaDocumentEntryDataClient t = new AsycudaDocumentEntryDataClient())
                    {
                        var res = await t.GetAsycudaDocumentEntryDataByEntryDataId(EntryDataId, includesLst).ConfigureAwait(continueOnCapturedContext: false);
                         if(res != null)
                        {
                            return res.Select(x => new AsycudaDocumentEntryData(x)).AsEnumerable();
					    }                
					    else
					    {
						    return null;
					    }                    
                    }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
        } 
         
		public decimal SumField(string whereExp, string sumExp)
        {
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                {
                    return t.SumField(whereExp,sumExp);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }

        public async Task<decimal> SumNav(string whereExp, Dictionary<string, string> navExp, string sumExp)
        {
            try
            {
                using (var t = new AsycudaDocumentEntryDataClient())
                {
                    return await t.SumNav(whereExp,navExp,sumExp).ConfigureAwait(false);
                }
            }
            catch (FaultException<ValidationFault> e)
            {
                throw new Exception(e.Detail.Message, e.InnerException);
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }

        }
    }
}

