// <autogenerated>
//   This file was generated by T4 code generator AllClientEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
//using Newtonsoft.Json;


using Core.Common.Client.DTO;
using TrackableEntities;
using TrackableEntities.Client;

namespace CounterPointQS.Client.DTO
{

   // [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace="http://www.insight-software.com/WaterNut")]
    public partial class CounterPointPOs : BaseEntity<CounterPointPOs>, ITrackable, IEquatable<CounterPointPOs>
    {
        [DataMember]
        public string PurchaseOrderNo
		{ 
		    get { return _PurchaseOrderNo; }
			set
			{
			    if (value == _PurchaseOrderNo) return;
				_PurchaseOrderNo = value;
				NotifyPropertyChanged();//m => this.PurchaseOrderNo
			}
		}
        private string _PurchaseOrderNo;

        [DataMember]
        public System.DateTime Date
		{ 
		    get { return _Date; }
			set
			{
			    if (value == _Date) return;
				_Date = value;
				NotifyPropertyChanged();//m => this.Date
			}
		}
        private System.DateTime _Date;

        [DataMember]
        public int LineNumber
		{ 
		    get { return _LineNumber; }
			set
			{
			    if (value == _LineNumber) return;
				_LineNumber = value;
				NotifyPropertyChanged();//m => this.LineNumber
			}
		}
        private int _LineNumber;

        [DataMember]
        public Nullable<bool> Downloaded
		{ 
		    get { return _Downloaded; }
			set
			{
			    if (value == _Downloaded) return;
				_Downloaded = value;
				NotifyPropertyChanged();//m => this.Downloaded
			}
		}
        private Nullable<bool> _Downloaded;

       
   //     [DataMember]
   //     public TrackingState TrackingState { get; set; }

   //     [DataMember]
   //     public ICollection<string> ModifiedProperties { get; set; }
        
    //  [DataMember]//JsonProperty, 
    //	private Guid EntityIdentifier { get; set; }
    
    //	[DataMember]//JsonProperty, 
    //	private Guid _entityIdentity = default(Guid);
    
    	bool IEquatable<CounterPointPOs>.Equals(CounterPointPOs other)
    	{
    		if (EntityIdentifier != default(Guid))
    			return EntityIdentifier == other.EntityIdentifier;
    		return false;
    	}
    }
}



