// <autogenerated>
//   This file was generated by T4 code generator DomainInterface.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;



namespace WaterNut.Interfaces
{

    //public partial interface IEntryData //AllocationDS|EntryDataDetails
    //{

    //    String EntryDataId { get; set; }
    //    DateTime EntryDataDate { get; set; }
        
    //}

}

