// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using AdjustmentQS.Client.DTO;


namespace AdjustmentQS.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface IInventoryItemService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<InventoryItem>> GetInventoryItems(List<string> includesLst = null);

        [OperationContract]
        Task<InventoryItem> GetInventoryItemByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<InventoryItem>> GetInventoryItemsByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<InventoryItem>> GetInventoryItemsByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<InventoryItem>> GetInventoryItemsByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<InventoryItem>> GetInventoryItemsByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<InventoryItem>> GetInventoryItemsByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<InventoryItem> UpdateInventoryItem(InventoryItem entity);

        [OperationContract]
        Task<InventoryItem> CreateInventoryItem(InventoryItem entity);

        [OperationContract]
        Task<bool> DeleteInventoryItem(string id);

        [OperationContract]
        Task<bool> RemoveSelectedInventoryItem(IEnumerable<string> selectedInventoryItem);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<InventoryItem>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<InventoryItem>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				[OperationContract]
		Task<IEnumerable<InventoryItem>> GetInventoryItemByApplicationSettingsId(string ApplicationSettingsId, List<string> includesLst = null);
        
  		
    }
}

