// <autogenerated>
//   This file was generated by T4 code generator AllDataSpaceViewModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.Threading.Tasks;
//using SimpleMvvmToolkit;
using DocumentDS.Business.Entities;
using DocumentDS.Business.Services;




namespace WaterNut.DataSpace.DocumentDS.DataModels
{
	public partial class xcuda_Export_releaseDataModel_AutoGen 
	{
        private static readonly xcuda_Export_releaseDataModel_AutoGen instance;
        static xcuda_Export_releaseDataModel_AutoGen()
        {
            instance = new xcuda_Export_releaseDataModel_AutoGen();
        }

        public static  xcuda_Export_releaseDataModel_AutoGen Instance
        {
            get { return instance; }
        }

       //Search Entities 
        public async Task<IEnumerable<xcuda_Export_release>> Searchxcuda_Export_release(List<string> lst, List<string> includeLst = null )
        {
            using (var ctx = new xcuda_Export_releaseService())
            {
                return await ctx.Getxcuda_Export_releaseByExpressionLst(lst, includeLst).ConfigureAwait(false);
            }
        }

    }
}
		
