// <autogenerated>
//   This file was generated by T4 code generator AllBusinessEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
//using Newtonsoft.Json;

using Core.Common.Business.Entities;
using WaterNut.Interfaces;
using TrackableEntities;

namespace EntryDataDS.Business.Entities
{

    //[JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace="http://www.insight-software.com/WaterNut")]
    public partial class ShipmentFreight : BaseEntity<ShipmentFreight>, ITrackable 
    {
        partial void AutoGenStartUp() //ShipmentFreight()
        {
            this.ShipmentFreightDetails = new List<ShipmentFreightDetails>();
            this.ShipmentAttachedFreight = new List<ShipmentAttachedFreight>();
            this.ShipmentBLFreight = new List<ShipmentBLFreight>();
        }

        [DataMember]
        public int Id 
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        int _id;
        [DataMember]
        public string BLNumber 
        {
            get
            {
                return _blnumber;
            }
            set
            {
                _blnumber = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _blnumber;
        [DataMember]
        public string Consignee 
        {
            get
            {
                return _consignee;
            }
            set
            {
                _consignee = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _consignee;
        [DataMember]
        public string InvoiceNumber 
        {
            get
            {
                return _invoicenumber;
            }
            set
            {
                _invoicenumber = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _invoicenumber;
        [DataMember]
        public System.DateTime InvoiceDate 
        {
            get
            {
                return _invoicedate;
            }
            set
            {
                _invoicedate = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        System.DateTime _invoicedate;
        [DataMember]
        public System.DateTime DueDate 
        {
            get
            {
                return _duedate;
            }
            set
            {
                _duedate = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        System.DateTime _duedate;
        [DataMember]
        public double InvoiceTotal 
        {
            get
            {
                return _invoicetotal;
            }
            set
            {
                _invoicetotal = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        double _invoicetotal;
        [DataMember]
        public System.DateTime ETA 
        {
            get
            {
                return _eta;
            }
            set
            {
                _eta = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        System.DateTime _eta;
        [DataMember]
        public Nullable<int> EmailId 
        {
            get
            {
                return _emailid;
            }
            set
            {
                _emailid = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        Nullable<int> _emailid;
        [DataMember]
        public string SourceFile 
        {
            get
            {
                return _sourcefile;
            }
            set
            {
                _sourcefile = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _sourcefile;
        [DataMember]
        public int FileTypeId 
        {
            get
            {
                return _filetypeid;
            }
            set
            {
                _filetypeid = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        int _filetypeid;
        [DataMember]
        public Nullable<int> ApplicationSettingsId 
        {
            get
            {
                return _applicationsettingsid;
            }
            set
            {
                _applicationsettingsid = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        Nullable<int> _applicationsettingsid;
        [DataMember]
        public string Currency 
        {
            get
            {
                return _currency;
            }
            set
            {
                _currency = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _currency;
        [DataMember]
        public List<ShipmentFreightDetails> ShipmentFreightDetails { get; set; }
        [DataMember]
        public List<ShipmentAttachedFreight> ShipmentAttachedFreight { get; set; }
        [DataMember]
        public List<ShipmentBLFreight> ShipmentBLFreight { get; set; }

 //       [DataMember]
 //       public TrackingState TrackingState { get; set; }
 //       [DataMember]
 //       public ICollection<string> ModifiedProperties { get; set; }
//        [DataMember]//JsonProperty,
 //       private Guid EntityIdentifier { get; set; }
    }
}


