// <autogenerated>
//   This file was generated by T4 code generator AllClientModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using CoreEntities;
using CoreEntities.Client.Entities;
//using WaterNut.Client.Services;
using CoreEntities.Client.Services;
using System.Linq;

namespace EntryDataQS.Client.Entities
{
    public partial class ContainerEntryData
    {
 
    }
   
}
		