// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using CounterPointQS.Client.DTO;


namespace CounterPointQS.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface ICounterPointPOsService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<CounterPointPOs>> GetCounterPointPOs(List<string> includesLst = null);

        [OperationContract]
        Task<CounterPointPOs> GetCounterPointPOsByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<CounterPointPOs>> GetCounterPointPOsByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<CounterPointPOs>> GetCounterPointPOsByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<CounterPointPOs>> GetCounterPointPOsByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<CounterPointPOs>> GetCounterPointPOsByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<CounterPointPOs>> GetCounterPointPOsByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<CounterPointPOs> UpdateCounterPointPOs(CounterPointPOs entity);

        [OperationContract]
        Task<CounterPointPOs> CreateCounterPointPOs(CounterPointPOs entity);

        [OperationContract]
        Task<bool> DeleteCounterPointPOs(string id);

        [OperationContract]
        Task<bool> RemoveSelectedCounterPointPOs(IEnumerable<string> selectedCounterPointPOs);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<CounterPointPOs>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<CounterPointPOs>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				
    }
}

