// <autogenerated>
//   This file was generated by T4 code generator AllClientEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
//using Newtonsoft.Json;


using Core.Common.Client.DTO;
using TrackableEntities;
using TrackableEntities.Client;

namespace CoreEntities.Client.DTO
{

   // [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace="http://www.insight-software.com/WaterNut")]
    public partial class ParameterSet : BaseEntity<ParameterSet>, ITrackable, IEquatable<ParameterSet>
    {
        [DataMember]
        public int Id
		{ 
		    get { return _Id; }
			set
			{
			    if (value == _Id) return;
				_Id = value;
				NotifyPropertyChanged();//m => this.Id
			}
		}
        private int _Id;

        [DataMember]
        public string Name
		{ 
		    get { return _Name; }
			set
			{
			    if (value == _Name) return;
				_Name = value;
				NotifyPropertyChanged();//m => this.Name
			}
		}
        private string _Name;

       
        [DataMember]
        public ChangeTrackingCollection<ParameterSetParameters> ParameterSetParameters
		{
		    get { return _ParameterSetParameters; }
			set
			{
			    if (Equals(value, _ParameterSetParameters)) return;
				_ParameterSetParameters = value;
				NotifyPropertyChanged();//m => this.ParameterSetParameters
			}
		}
        private ChangeTrackingCollection<ParameterSetParameters> _ParameterSetParameters = new ChangeTrackingCollection<ParameterSetParameters>();

        [DataMember]
        public ChangeTrackingCollection<SessionSchedule> SessionSchedule
		{
		    get { return _SessionSchedule; }
			set
			{
			    if (Equals(value, _SessionSchedule)) return;
				_SessionSchedule = value;
				NotifyPropertyChanged();//m => this.SessionSchedule
			}
		}
        private ChangeTrackingCollection<SessionSchedule> _SessionSchedule = new ChangeTrackingCollection<SessionSchedule>();

   //     [DataMember]
   //     public TrackingState TrackingState { get; set; }

   //     [DataMember]
   //     public ICollection<string> ModifiedProperties { get; set; }
        
    //  [DataMember]//JsonProperty, 
    //	private Guid EntityIdentifier { get; set; }
    
    //	[DataMember]//JsonProperty, 
    //	private Guid _entityIdentity = default(Guid);
    
    	bool IEquatable<ParameterSet>.Equals(ParameterSet other)
    	{
    		if (EntityIdentifier != default(Guid))
    			return EntityIdentifier == other.EntityIdentifier;
    		return false;
    	}
    }
}



