// <autogenerated>
//   This file was generated by T4 code generator AllClientEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Diagnostics;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using TrackableEntities.Client;
using Core.Common.Client.Entities;
using OCR.Client.DTO;


using Core.Common.Validation;

namespace OCR.Client.Entities
{
       public partial class OCR_FailedFields: BaseEntity<OCR_FailedFields>
    {
        DTO.OCR_FailedFields ocr_failedfields;
        public OCR_FailedFields(DTO.OCR_FailedFields dto )
        {
              ocr_failedfields = dto;
             _changeTracker = new ChangeTrackingCollection<DTO.OCR_FailedFields>(ocr_failedfields);

        }

        public DTO.OCR_FailedFields DTO
        {
            get
            {
             return ocr_failedfields;
            }
            set
            {
                ocr_failedfields = value;
            }
        }
       [RequiredValidationAttribute(ErrorMessage= " is required")]
       
public int Id
		{ 
		    get { return this.ocr_failedfields.Id; }
			set
			{
			    if (value == this.ocr_failedfields.Id) return;
				this.ocr_failedfields.Id = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Id");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "FailedLineEvent is required")]
       
public int FailedLineEventId
		{ 
		    get { return this.ocr_failedfields.FailedLineEventId; }
			set
			{
			    if (value == this.ocr_failedfields.FailedLineEventId) return;
				this.ocr_failedfields.FailedLineEventId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("FailedLineEventId");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "Field is required")]
       
public int FieldId
		{ 
		    get { return this.ocr_failedfields.FieldId; }
			set
			{
			    if (value == this.ocr_failedfields.FieldId) return;
				this.ocr_failedfields.FieldId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("FieldId");
			}
		}
     

       private OCR_FailedLines _OCR_FailedLines;
        public  OCR_FailedLines OCR_FailedLines
		{
		    get
               { 
                  if (this.ocr_failedfields != null)
                   {
                       if (_OCR_FailedLines != null)
                       {
                           if (this.ocr_failedfields.OCR_FailedLines !=
                               _OCR_FailedLines.DTO)
                           {
                                if (this.ocr_failedfields.OCR_FailedLines  != null)
                               _OCR_FailedLines = new OCR_FailedLines(this.ocr_failedfields.OCR_FailedLines);
                           }
                       }
                       else
                       {
                             if (this.ocr_failedfields.OCR_FailedLines  != null)
                           _OCR_FailedLines = new OCR_FailedLines(this.ocr_failedfields.OCR_FailedLines);
                       }
                   }


             //       if (_OCR_FailedLines != null) return _OCR_FailedLines;
                       
             //       var i = new OCR_FailedLines(){TrackingState = TrackingState.Added};
			//		//if (this.ocr_failedfields.OCR_FailedLines == null) Debugger.Break();
			//		if (this.ocr_failedfields.OCR_FailedLines != null)
            //        {
            //           i. = this.ocr_failedfields.OCR_FailedLines;
            //        }
            //        else
            //        {
            //            this.ocr_failedfields.OCR_FailedLines = i.;
             //       }
                           
            //        _OCR_FailedLines = i;
                     
                    return _OCR_FailedLines;
               }
			set
			{
			    if (value == _OCR_FailedLines) return;
                _OCR_FailedLines = value;
                if(value != null)
                     this.ocr_failedfields.OCR_FailedLines = value.DTO;
				if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
                NotifyPropertyChanged("OCR_FailedLines");
			}
		}
        

       private Fields _OCR_Fields;
        public  Fields OCR_Fields
		{
		    get
               { 
                  if (this.ocr_failedfields != null)
                   {
                       if (_OCR_Fields != null)
                       {
                           if (this.ocr_failedfields.OCR_Fields !=
                               _OCR_Fields.DTO)
                           {
                                if (this.ocr_failedfields.OCR_Fields  != null)
                               _OCR_Fields = new Fields(this.ocr_failedfields.OCR_Fields);
                           }
                       }
                       else
                       {
                             if (this.ocr_failedfields.OCR_Fields  != null)
                           _OCR_Fields = new Fields(this.ocr_failedfields.OCR_Fields);
                       }
                   }


             //       if (_OCR_Fields != null) return _OCR_Fields;
                       
             //       var i = new Fields(){TrackingState = TrackingState.Added};
			//		//if (this.ocr_failedfields.OCR_Fields == null) Debugger.Break();
			//		if (this.ocr_failedfields.OCR_Fields != null)
            //        {
            //           i. = this.ocr_failedfields.OCR_Fields;
            //        }
            //        else
            //        {
            //            this.ocr_failedfields.OCR_Fields = i.;
             //       }
                           
            //        _OCR_Fields = i;
                     
                    return _OCR_Fields;
               }
			set
			{
			    if (value == _OCR_Fields) return;
                _OCR_Fields = value;
                if(value != null)
                     this.ocr_failedfields.OCR_Fields = value.DTO;
				if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
                NotifyPropertyChanged("OCR_Fields");
			}
		}
        


        ChangeTrackingCollection<DTO.OCR_FailedFields> _changeTracker;    
        public ChangeTrackingCollection<DTO.OCR_FailedFields> ChangeTracker
        {
            get
            {
                return _changeTracker;
            }
        }

        public new TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.DTO.TrackingState;
            }
            set
            {
                this.DTO.TrackingState = value;
                NotifyPropertyChanged("TrackingState");
            }
        }

    }
}


