// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using CoreEntities.Client.DTO;


namespace CoreEntities.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface ITODO_SubmitDiscrepanciesToCustomsService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustoms(List<string> includesLst = null);

        [OperationContract]
        Task<TODO_SubmitDiscrepanciesToCustoms> GetTODO_SubmitDiscrepanciesToCustomsByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<TODO_SubmitDiscrepanciesToCustoms> UpdateTODO_SubmitDiscrepanciesToCustoms(TODO_SubmitDiscrepanciesToCustoms entity);

        [OperationContract]
        Task<TODO_SubmitDiscrepanciesToCustoms> CreateTODO_SubmitDiscrepanciesToCustoms(TODO_SubmitDiscrepanciesToCustoms entity);

        [OperationContract]
        Task<bool> DeleteTODO_SubmitDiscrepanciesToCustoms(string id);

        [OperationContract]
        Task<bool> RemoveSelectedTODO_SubmitDiscrepanciesToCustoms(IEnumerable<string> selectedTODO_SubmitDiscrepanciesToCustoms);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				[OperationContract]
		Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByAsycudaDocumentSetId(string AsycudaDocumentSetId, List<string> includesLst = null);
        
  		[OperationContract]
		Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByApplicationSettingsId(string ApplicationSettingsId, List<string> includesLst = null);
        
  		[OperationContract]
		Task<IEnumerable<TODO_SubmitDiscrepanciesToCustoms>> GetTODO_SubmitDiscrepanciesToCustomsByEmailId(string EmailId, List<string> includesLst = null);
        
  		
    }
}

