// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading.Tasks;
using Core.Common.Contracts;
using CoreEntities.Client.DTO;


namespace CoreEntities.Client.Contracts
{
    [ServiceContract (Namespace="http://www.insight-software.com/WaterNut")]
    public partial interface ITODO_LICToCreateService : IClientService
    {
        [OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreate(List<string> includesLst = null);

        [OperationContract]
        Task<TODO_LICToCreate> GetTODO_LICToCreateByKey(string id, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreateByExpression(string exp, List<string> includesLst = null);

		[OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreateByExpressionLst(List<string> expLst, List<string> includesLst = null);

		[OperationContract]
		Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreateByExpressionNav(string exp,
														 Dictionary<string, string> navExp, List<string> includesLst = null);        
        [OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreateByBatch(string exp,
                                                                        int totalrow, List<string> includesLst = null);
        [OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> GetTODO_LICToCreateByBatchExpressionLst(List<string> expLst,
                                                                        int totalrow, List<string> includesLst = null);

		[OperationContract]
        Task<TODO_LICToCreate> UpdateTODO_LICToCreate(TODO_LICToCreate entity);

        [OperationContract]
        Task<TODO_LICToCreate> CreateTODO_LICToCreate(TODO_LICToCreate entity);

        [OperationContract]
        Task<bool> DeleteTODO_LICToCreate(string id);

        [OperationContract]
        Task<bool> RemoveSelectedTODO_LICToCreate(IEnumerable<string> selectedTODO_LICToCreate);

		// Virtural List Implementation

        [OperationContract]
        Task<int> CountByExpressionLst(List<string> expLst);
    
		[OperationContract]
        Task<int> Count(string exp);

		[OperationContract]
        Task<int> CountNav(string exp, Dictionary<string, string> navExp);

        [OperationContract]
        Task<IEnumerable<TODO_LICToCreate>> LoadRange(int startIndex, int count, string exp);

		[OperationContract]
		Task<IEnumerable<TODO_LICToCreate>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null);

		[OperationContract]
		decimal SumField(string whereExp, string field);
        
        [OperationContract]
        Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field);

		[OperationContract]
		string MinField(string whereExp, string field);

				
    }
}

