declare @dbname varchar(50), @Alter_TEMPLATE VARCHAR(MAX)
set @dbname = '[AutoBot-EnterpriseDB]'

set @Alter_TEMPLATE = 'ALTER DATABASE {DBNAME} SET EMERGENCY;
ALTER DATABASE {DBNAME} set single_user
DBCC CHECKDB ({DBNAME}, REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS;
ALTER DATABASE {DBNAME} set multi_user'


DECLARE @SQL_SCRIPT VARCHAR(MAX)

SET @SQL_SCRIPT = REPLACE(@Alter_TEMPLATE, '{DBNAME}', @dbname)
EXECUTE (@SQL_SCRIPT)
GO
