// <autogenerated>
//   This file was generated by T4 code generator AllClientEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Diagnostics;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using TrackableEntities.Client;
using Core.Common.Client.Entities;
using CoreEntities.Client.DTO;


using Core.Common.Validation;

namespace CoreEntities.Client.Entities
{
       public partial class TODO_PODocSetToExport: BaseEntity<TODO_PODocSetToExport>
    {
        DTO.TODO_PODocSetToExport todo_podocsettoexport;
        public TODO_PODocSetToExport(DTO.TODO_PODocSetToExport dto )
        {
              todo_podocsettoexport = dto;
             _changeTracker = new ChangeTrackingCollection<DTO.TODO_PODocSetToExport>(todo_podocsettoexport);

        }

        public DTO.TODO_PODocSetToExport DTO
        {
            get
            {
             return todo_podocsettoexport;
            }
            set
            {
                todo_podocsettoexport = value;
            }
        }
       [RequiredValidationAttribute(ErrorMessage= "AsycudaDocumentSet is required")]
       
public int AsycudaDocumentSetId
		{ 
		    get { return this.todo_podocsettoexport.AsycudaDocumentSetId; }
			set
			{
			    if (value == this.todo_podocsettoexport.AsycudaDocumentSetId) return;
				this.todo_podocsettoexport.AsycudaDocumentSetId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("AsycudaDocumentSetId");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "ApplicationSettings is required")]
       
public int ApplicationSettingsId
		{ 
		    get { return this.todo_podocsettoexport.ApplicationSettingsId; }
			set
			{
			    if (value == this.todo_podocsettoexport.ApplicationSettingsId) return;
				this.todo_podocsettoexport.ApplicationSettingsId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("ApplicationSettingsId");
			}
		}
     

       
       
                
                [MaxLength(3, ErrorMessage = "Country_of_origin_code has a max length of 3 letters ")]
public string Country_of_origin_code
		{ 
		    get { return this.todo_podocsettoexport.Country_of_origin_code; }
			set
			{
			    if (value == this.todo_podocsettoexport.Country_of_origin_code) return;
				this.todo_podocsettoexport.Country_of_origin_code = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Country_of_origin_code");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "Currency_Code is required")]
       
                
                [MaxLength(3, ErrorMessage = "Currency_Code has a max length of 3 letters ")]
public string Currency_Code
		{ 
		    get { return this.todo_podocsettoexport.Currency_Code; }
			set
			{
			    if (value == this.todo_podocsettoexport.Currency_Code) return;
				this.todo_podocsettoexport.Currency_Code = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Currency_Code");
			}
		}
     

       
       
                
                [MaxLength(50, ErrorMessage = "Manifest_Number has a max length of 50 letters ")]
public string Manifest_Number
		{ 
		    get { return this.todo_podocsettoexport.Manifest_Number; }
			set
			{
			    if (value == this.todo_podocsettoexport.Manifest_Number) return;
				this.todo_podocsettoexport.Manifest_Number = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Manifest_Number");
			}
		}
     

       
       
                
                [MaxLength(50, ErrorMessage = "BLNumber has a max length of 50 letters ")]
public string BLNumber
		{ 
		    get { return this.todo_podocsettoexport.BLNumber; }
			set
			{
			    if (value == this.todo_podocsettoexport.BLNumber) return;
				this.todo_podocsettoexport.BLNumber = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("BLNumber");
			}
		}
     

       
       
                
                [MaxLength(10, ErrorMessage = "Type_of_declaration has a max length of 10 letters ")]
public string Type_of_declaration
		{ 
		    get { return this.todo_podocsettoexport.Type_of_declaration; }
			set
			{
			    if (value == this.todo_podocsettoexport.Type_of_declaration) return;
				this.todo_podocsettoexport.Type_of_declaration = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Type_of_declaration");
			}
		}
     

       
       
                
                [MaxLength(10, ErrorMessage = "Declaration_gen_procedure_code has a max length of 10 letters ")]
public string Declaration_gen_procedure_code
		{ 
		    get { return this.todo_podocsettoexport.Declaration_gen_procedure_code; }
			set
			{
			    if (value == this.todo_podocsettoexport.Declaration_gen_procedure_code) return;
				this.todo_podocsettoexport.Declaration_gen_procedure_code = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Declaration_gen_procedure_code");
			}
		}
     

       
       
                
                [MaxLength(50, ErrorMessage = "Declarant_Reference_Number has a max length of 50 letters ")]
public string Declarant_Reference_Number
		{ 
		    get { return this.todo_podocsettoexport.Declarant_Reference_Number; }
			set
			{
			    if (value == this.todo_podocsettoexport.Declarant_Reference_Number) return;
				this.todo_podocsettoexport.Declarant_Reference_Number = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("Declarant_Reference_Number");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> TotalInvoices
		{ 
		    get { return this.todo_podocsettoexport.TotalInvoices; }
			set
			{
			    if (value == this.todo_podocsettoexport.TotalInvoices) return;
				this.todo_podocsettoexport.TotalInvoices = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("TotalInvoices");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "NeedC71 is required")]
       [NumberValidationAttribute]
public int NeedC71
		{ 
		    get { return this.todo_podocsettoexport.NeedC71; }
			set
			{
			    if (value == this.todo_podocsettoexport.NeedC71) return;
				this.todo_podocsettoexport.NeedC71 = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("NeedC71");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "NeedLicense is required")]
       [NumberValidationAttribute]
public int NeedLicense
		{ 
		    get { return this.todo_podocsettoexport.NeedLicense; }
			set
			{
			    if (value == this.todo_podocsettoexport.NeedLicense) return;
				this.todo_podocsettoexport.NeedLicense = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("NeedLicense");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> DocumentsCount
		{ 
		    get { return this.todo_podocsettoexport.DocumentsCount; }
			set
			{
			    if (value == this.todo_podocsettoexport.DocumentsCount) return;
				this.todo_podocsettoexport.DocumentsCount = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("DocumentsCount");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<double> InvoiceTotal
		{ 
		    get { return this.todo_podocsettoexport.InvoiceTotal; }
			set
			{
			    if (value == this.todo_podocsettoexport.InvoiceTotal) return;
				this.todo_podocsettoexport.InvoiceTotal = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("InvoiceTotal");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> LicenseLines
		{ 
		    get { return this.todo_podocsettoexport.LicenseLines; }
			set
			{
			    if (value == this.todo_podocsettoexport.LicenseLines) return;
				this.todo_podocsettoexport.LicenseLines = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("LicenseLines");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<double> TotalCIF
		{ 
		    get { return this.todo_podocsettoexport.TotalCIF; }
			set
			{
			    if (value == this.todo_podocsettoexport.TotalCIF) return;
				this.todo_podocsettoexport.TotalCIF = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("TotalCIF");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> HasC71
		{ 
		    get { return this.todo_podocsettoexport.HasC71; }
			set
			{
			    if (value == this.todo_podocsettoexport.HasC71) return;
				this.todo_podocsettoexport.HasC71 = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("HasC71");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> HasLicense
		{ 
		    get { return this.todo_podocsettoexport.HasLicense; }
			set
			{
			    if (value == this.todo_podocsettoexport.HasLicense) return;
				this.todo_podocsettoexport.HasLicense = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("HasLicense");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<double> TotalFreight
		{ 
		    get { return this.todo_podocsettoexport.TotalFreight; }
			set
			{
			    if (value == this.todo_podocsettoexport.TotalFreight) return;
				this.todo_podocsettoexport.TotalFreight = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("TotalFreight");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> ClassifiedLines
		{ 
		    get { return this.todo_podocsettoexport.ClassifiedLines; }
			set
			{
			    if (value == this.todo_podocsettoexport.ClassifiedLines) return;
				this.todo_podocsettoexport.ClassifiedLines = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("ClassifiedLines");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> TotalLines
		{ 
		    get { return this.todo_podocsettoexport.TotalLines; }
			set
			{
			    if (value == this.todo_podocsettoexport.TotalLines) return;
				this.todo_podocsettoexport.TotalLines = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("TotalLines");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> EntryPackages
		{ 
		    get { return this.todo_podocsettoexport.EntryPackages; }
			set
			{
			    if (value == this.todo_podocsettoexport.EntryPackages) return;
				this.todo_podocsettoexport.EntryPackages = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("EntryPackages");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<double> TotalWeight
		{ 
		    get { return this.todo_podocsettoexport.TotalWeight; }
			set
			{
			    if (value == this.todo_podocsettoexport.TotalWeight) return;
				this.todo_podocsettoexport.TotalWeight = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("TotalWeight");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "FreightCurrencyCode is required")]
       
                
                [MaxLength(3, ErrorMessage = "FreightCurrencyCode has a max length of 3 letters ")]
public string FreightCurrencyCode
		{ 
		    get { return this.todo_podocsettoexport.FreightCurrencyCode; }
			set
			{
			    if (value == this.todo_podocsettoexport.FreightCurrencyCode) return;
				this.todo_podocsettoexport.FreightCurrencyCode = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("FreightCurrencyCode");
			}
		}
     

       
       [NumberValidationAttribute]
public Nullable<int> ExpectedEntries
		{ 
		    get { return this.todo_podocsettoexport.ExpectedEntries; }
			set
			{
			    if (value == this.todo_podocsettoexport.ExpectedEntries) return;
				this.todo_podocsettoexport.ExpectedEntries = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("ExpectedEntries");
			}
		}
     


        ChangeTrackingCollection<DTO.TODO_PODocSetToExport> _changeTracker;    
        public ChangeTrackingCollection<DTO.TODO_PODocSetToExport> ChangeTracker
        {
            get
            {
                return _changeTracker;
            }
        }

        public new TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.DTO.TrackingState;
            }
            set
            {
                this.DTO.TrackingState = value;
                NotifyPropertyChanged("TrackingState");
            }
        }

    }
}


