// <autogenerated>
//   This file was generated by T4 code generator AllClientEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Diagnostics;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using TrackableEntities.Client;
using Core.Common.Client.Entities;
using CoreEntities.Client.DTO;


using Core.Common.Validation;

namespace CoreEntities.Client.Entities
{
       public partial class ToDo_POToXML_Recreate: BaseEntity<ToDo_POToXML_Recreate>
    {
        DTO.ToDo_POToXML_Recreate todo_potoxml_recreate;
        public ToDo_POToXML_Recreate(DTO.ToDo_POToXML_Recreate dto )
        {
              todo_potoxml_recreate = dto;
             _changeTracker = new ChangeTrackingCollection<DTO.ToDo_POToXML_Recreate>(todo_potoxml_recreate);

        }

        public DTO.ToDo_POToXML_Recreate DTO
        {
            get
            {
             return todo_potoxml_recreate;
            }
            set
            {
                todo_potoxml_recreate = value;
            }
        }
       [RequiredValidationAttribute(ErrorMessage= "EntryDataDetails is required")]
       
public int EntryDataDetailsId
		{ 
		    get { return this.todo_potoxml_recreate.EntryDataDetailsId; }
			set
			{
			    if (value == this.todo_potoxml_recreate.EntryDataDetailsId) return;
				this.todo_potoxml_recreate.EntryDataDetailsId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("EntryDataDetailsId");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "ApplicationSettings is required")]
       
public int ApplicationSettingsId
		{ 
		    get { return this.todo_potoxml_recreate.ApplicationSettingsId; }
			set
			{
			    if (value == this.todo_potoxml_recreate.ApplicationSettingsId) return;
				this.todo_potoxml_recreate.ApplicationSettingsId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("ApplicationSettingsId");
			}
		}
     

       [RequiredValidationAttribute(ErrorMessage= "AsycudaDocumentSet is required")]
       
public int AsycudaDocumentSetId
		{ 
		    get { return this.todo_potoxml_recreate.AsycudaDocumentSetId; }
			set
			{
			    if (value == this.todo_potoxml_recreate.AsycudaDocumentSetId) return;
				this.todo_potoxml_recreate.AsycudaDocumentSetId = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("AsycudaDocumentSetId");
			}
		}
     

       
       
public Nullable<bool> IsClassified
		{ 
		    get { return this.todo_potoxml_recreate.IsClassified; }
			set
			{
			    if (value == this.todo_potoxml_recreate.IsClassified) return;
				this.todo_potoxml_recreate.IsClassified = value;
                if(this.TrackingState == TrackableEntities.TrackingState.Unchanged)this.TrackingState = TrackableEntities.TrackingState.Modified;
				NotifyPropertyChanged("IsClassified");
			}
		}
     


        ChangeTrackingCollection<DTO.ToDo_POToXML_Recreate> _changeTracker;    
        public ChangeTrackingCollection<DTO.ToDo_POToXML_Recreate> ChangeTracker
        {
            get
            {
                return _changeTracker;
            }
        }

        public new TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.DTO.TrackingState;
            }
            set
            {
                this.DTO.TrackingState = value;
                NotifyPropertyChanged("TrackingState");
            }
        }

    }
}


