// <autogenerated>
//   This file was generated by T4 code generator AllDataSpaceViewModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.Threading.Tasks;
using System.Collections.ObjectModel;
using System.Linq;
using SimpleMvvmToolkit;
using TrackableEntities;
using System;
using EntryDataDS.Business.Entities;
using EntryDataDS.Business.Services;




namespace WaterNut.DataSpace.EntryDataDS.DataModels
{
	public partial class AsycudaDocumentEntryDataDataModel_AutoGen 
	{
        private static readonly AsycudaDocumentEntryDataDataModel_AutoGen instance;
        static AsycudaDocumentEntryDataDataModel_AutoGen()
        {
            instance = new AsycudaDocumentEntryDataDataModel_AutoGen();
        }

        public static  AsycudaDocumentEntryDataDataModel_AutoGen Instance
        {
            get { return instance; }
        }

       //Search Entities 
        public async Task<IEnumerable<AsycudaDocumentEntryData>> SearchAsycudaDocumentEntryData(List<string> lst, List<string> includeLst = null )
        {
            using (var ctx = new AsycudaDocumentEntryDataService())
            {
                return await ctx.GetAsycudaDocumentEntryDataByExpressionLst(lst, includeLst).ConfigureAwait(false);
            }
        }

    }
}
		
