// <autogenerated>
//   This file was generated by T4 code generator AllBusinessEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
//using Newtonsoft.Json;

using Core.Common.Business.Entities;
using WaterNut.Interfaces;
using TrackableEntities;

namespace DocumentItemDS.Business.Entities
{
    //[JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace="http://www.insight-software.com/WaterNut")]
    public partial class xcuda_Packages : BaseEntity<xcuda_Packages>, ITrackable 
    {
        [DataMember]
        public double Number_of_packages 
        {
            get
            {
                return _number_of_packages;
            }
            set
            {
                _number_of_packages = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        double _number_of_packages;
        [DataMember]
        public string Kind_of_packages_code 
        {
            get
            {
                return _kind_of_packages_code;
            }
            set
            {
                _kind_of_packages_code = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _kind_of_packages_code;
        [DataMember]
        public string Kind_of_packages_name 
        {
            get
            {
                return _kind_of_packages_name;
            }
            set
            {
                _kind_of_packages_name = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _kind_of_packages_name;
        [DataMember]
        public int Packages_Id 
        {
            get
            {
                return _packages_id;
            }
            set
            {
                _packages_id = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        int _packages_id;
        [DataMember]
        public Nullable<int> Item_Id 
        {
            get
            {
                return _item_id;
            }
            set
            {
                _item_id = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        Nullable<int> _item_id;
        [DataMember]
        public string Marks1_of_packages 
        {
            get
            {
                return _marks1_of_packages;
            }
            set
            {
                _marks1_of_packages = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _marks1_of_packages;
        [DataMember]
        public string Marks2_of_packages 
        {
            get
            {
                return _marks2_of_packages;
            }
            set
            {
                _marks2_of_packages = value;
                //if(this.TrackingState == TrackingState.Unchanged) this.TrackingState = TrackingState.Modified;  
                NotifyPropertyChanged();
            }
        }
        string _marks2_of_packages;
        [DataMember]
        public xcuda_Item xcuda_Item { get; set; }

 //       [DataMember]
 //       public TrackingState TrackingState { get; set; }
 //       [DataMember]
 //       public ICollection<string> ModifiedProperties { get; set; }
//        [DataMember]//JsonProperty,
 //       private Guid EntityIdentifier { get; set; }
    }
}


