// <autogenerated>
//   This file was generated by T4 code generator AllClientModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Linq;
using CoreEntities.Client.Entities;
using CoreEntities.Client.Services;
//using WaterNut.Client.Services;
using CoreEntities.Client.Services;

using System;

namespace CoreEntities.Client.Entities
{
    public partial class InventoryItemAliasX
    {
       
       #region IIdentifiable Entities
        public override string EntityId
        {
            get
            {
                return this.AliasId.ToString();//this.AliasId == null?"0":			
            }
            set
            {
                this.AliasId = Convert.ToInt32(value);
            }
        }
        public string InventoryItemsExEntityName
        {
            get
            {
                return this.InventoryItemsEx == null ? "" : this.InventoryItemsEx.EntityName;
            }
            set
            {
                                if (string.IsNullOrEmpty(value)) return;
                string[] vals = value.Split(',');
               
                    using (InventoryItemXClient ctx = new InventoryItemXClient())
                    {
                        var dto = ctx.GetInventoryItemX().Result.AsEnumerable().FirstOrDefault(x => x.EntityName == value);
                        

                        if ( dto == null)
                        {
                            this.InventoryItemsEx = (InventoryItemX)new InventoryItemX().CreateEntityFromString(value);
							
							this.AliasId = Convert.ToInt32(this.InventoryItemsEx.InventoryItemId);
                            this.TrackingState=TrackableEntities.TrackingState.Modified;
                           NotifyPropertyChanged("AddInventoryItemsEx");
                        }
                        else
                        {
                            var obj = new InventoryItemX(dto);
                           if (this.InventoryItemsEx == null || this.InventoryItemsEx.EntityId != obj.EntityId) this.InventoryItemsEx = obj;
                           
                        }
                         


                    }
            
            }

      }
        public string ApplicationSettingsEntityName
        {
            get
            {
                return this.ApplicationSettings == null ? "" : this.ApplicationSettings.EntityName;
            }
            set
            {
                                if (string.IsNullOrEmpty(value)) return;
                string[] vals = value.Split(',');
               
                    using (ApplicationSettingsClient ctx = new ApplicationSettingsClient())
                    {
                        var dto = ctx.GetApplicationSettings().Result.AsEnumerable().FirstOrDefault(x => x.EntityName == value);
                        

                        if ( dto == null)
                        {
                            this.ApplicationSettings = (ApplicationSettings)new ApplicationSettings().CreateEntityFromString(value);
							
							this.ApplicationSettingsId = Convert.ToInt32(this.ApplicationSettings.ApplicationSettingsId);
                            this.TrackingState=TrackableEntities.TrackingState.Modified;
                           NotifyPropertyChanged("AddApplicationSettings");
                        }
                        else
                        {
                            var obj = new ApplicationSettings(dto);
                           if (this.ApplicationSettings == null || this.ApplicationSettings.EntityId != obj.EntityId) this.ApplicationSettings = obj;
                           
                        }
                         


                    }
            
            }

      }



         #endregion
    }
   
}
		