// <autogenerated>
//   This file was generated by T4 code generator ViewModels.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.Collections.Generic;
using System.Threading.Tasks;
//using SimpleMvvmToolkit;
using AllocationDS.Business.Entities;
using AllocationDS.Business.Services;




namespace WaterNut.DataSpace.AllocationDS.DataModels
{
	public partial class TariffCodesDataModel_AutoGen 
	{
        private static readonly TariffCodesDataModel_AutoGen instance;
        static TariffCodesDataModel_AutoGen()
        {
            instance = new TariffCodesDataModel_AutoGen();
        }

        public static  TariffCodesDataModel_AutoGen Instance
        {
            get { return instance; }
        }

       //Search Entities 
        public async Task<IEnumerable<TariffCodes>> SearchTariffCodes(List<string> lst, List<string> includeLst = null )
        {
            using (var ctx = new TariffCodesService())
            {
                return await ctx.GetTariffCodesByExpressionLst(lst, includeLst).ConfigureAwait(false);
            }
        }

    }
}
		
