// <autogenerated>
//   This file was generated by T4 code generator AllDomainInterface.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;



namespace WaterNut.Interfaces
{

		public partial interface IDocumentItem //CoreEntities|AsycudaDocumentItem
		{
		Int32 Item_Id {get;set;}
				Boolean? DoNotAllocate {get;set;}
				Boolean? AttributeOnlyAllocation {get;set;}
				String ItemNumber {get;set;}
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		        }

}

