// <autogenerated>
//   This file was generated by T4 code generator AllServices.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core;
using System.Data.SqlClient;
using System.Diagnostics;
using System.ServiceModel;
using System.Threading.Tasks;
//using System.Transactions;


using System.Linq.Dynamic;
using System.ComponentModel.Composition;
using EntryDataDS.Business.Entities;
using Core.Common.Contracts;
using Core.Common.Business.Services;
using Core.Common.UI;

using System.Data.Entity;
using System.Linq;
using TrackableEntities;
using TrackableEntities.Common;
using TrackableEntities.EF6;
using WaterNut.Interfaces;

namespace EntryDataDS.Business.Services
{
   [Export (typeof(IShipmentRiderExService))]
   [Export(typeof(IBusinessService))]
   [PartCreationPolicy(CreationPolicy.NonShared)]
   [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall,
                    ConcurrencyMode = ConcurrencyMode.Multiple)]
   
    public partial class ShipmentRiderExService : IShipmentRiderExService, IDisposable
    {
        //private readonly EntryDataDSContext dbContext;

        public bool StartTracking { get; set; }

        public ShipmentRiderExService()
        {
            try
            {
                // dbContext = new EntryDataDSContext(){StartTracking = StartTracking};
                StartTracking = false;
             }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault, new FaultReason(fault.Message));
            }
        }

        public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderEx(List<string> includesLst = null, bool tracking = true)
        {
            try
            {
            //using (var scope = new TransactionScope(TransactionScopeOption.Required,
                                   //new TransactionOptions() {IsolationLevel = IsolationLevel.ReadUncommitted}))
               // {
                  using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                  {
				    var set = AddIncludes(includesLst, dbContext);
                    IEnumerable<ShipmentRiderEx> entities = set.AsNoTracking().ToList();
                           //scope.Complete();
                            if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                            return Task.FromResult(entities);
                   }
                //}
             }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }


        public Task<ShipmentRiderEx> GetShipmentRiderExByKey(string Id, List<string> includesLst = null, bool tracking = true)
        {
            try
            {
			   if(string.IsNullOrEmpty(Id))return Task.FromResult<ShipmentRiderEx>(null); 
              using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
              {
                var i = Convert.ToInt32(Id);
				var set = AddIncludes(includesLst, dbContext);
                ShipmentRiderEx entity = set.AsNoTracking().SingleOrDefault(x => x.Id == i);
                if(tracking && entity != null) entity.StartTracking();
                return Task.FromResult(entity);
              }
             }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }


		 public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByExpression(string exp, List<string> includesLst = null, bool tracking = true)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
					if (string.IsNullOrEmpty(exp) || exp == "None") return Task.FromResult<IEnumerable<ShipmentRiderEx>>(new List<ShipmentRiderEx>());
					var set = AddIncludes(includesLst, dbContext);
                    if (exp == "All")
                    {
						var entities = set.AsNoTracking().ToList();

                        if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(entities); 
                    }
					else
					{
						var entities = set.AsNoTracking().Where(exp)
											.ToList();
                        if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(entities); 
											
					}
					
                }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

		 public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByExpressionLst(List<string> expLst, List<string> includesLst = null, bool tracking = true)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
					if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return Task.FromResult<IEnumerable<ShipmentRiderEx>>(new List<ShipmentRiderEx>());
					var set = AddIncludes(includesLst, dbContext);
                    if (expLst.FirstOrDefault() == "All")
                    {
						var entities = set.AsNoTracking().ToList(); 
                        if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(entities); 
                    }
					else
					{
						set = AddWheres(expLst, set);
						var entities = set.AsNoTracking().ToList();
                        if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(entities); 
											
					}
					
                }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

		public async Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByExpressionNav(string exp,
																							  Dictionary<string, string> navExp,
																							  List<string> includesLst = null, bool tracking = true)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if (string.IsNullOrEmpty(exp) || exp == "None") return new List<ShipmentRiderEx>();

                    if (exp == "All" && navExp.Count == 0)
                    {
                        var aentities = AddIncludes(includesLst, dbContext)
												.ToList();
                        if(tracking) aentities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return aentities; 
                    }
                    foreach (var itm in navExp)
                    {
                        switch (itm.Key)
                        {
                            case "ShipmentRider":
                                return
                                    await
                                        GetWhere<ShipmentRider>(dbContext, exp, itm.Value, "ShipmentRiderEx", "SelectMany", includesLst)
										.ConfigureAwait(continueOnCapturedContext: false);

                        }

                    }
					var set = AddIncludes(includesLst, dbContext);
                    var entities = set.AsNoTracking().Where(exp)
									.ToList();
                    if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                        return entities; 

                }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

        public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByBatch(string exp,
                                                                            int totalrow, List<string> includesLst = null, bool tracking = true)
        {
            try
            {

                var res = new ConcurrentQueue<List<ShipmentRiderEx>>();



                if (string.IsNullOrEmpty(exp) || exp == "None") return Task.FromResult<IEnumerable<ShipmentRiderEx>>(new List<ShipmentRiderEx>());


                var batchSize = 500;
                var batches = Convert.ToInt32(totalrow / batchSize);

                if (totalrow % batchSize > 0) batches += 1;
                var exceptions = new ConcurrentQueue<Exception>();
                Parallel.For(0, batches,
                   new ParallelOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount * 2 },
                    bat =>
                    //  for (int bat = 0; bat < batches; bat++)
                    {
                        try
                        {
                            using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                            {
                                dbContext.Database.CommandTimeout = 0;
                                dbContext.Configuration.AutoDetectChangesEnabled = false;
                                //dbContext.Configuration.LazyLoadingEnabled = true;
                                var set = AddIncludes(includesLst, dbContext);
                                IQueryable<ShipmentRiderEx> dset;
                                if (exp == "All")
                                {
                                    dset = set.OrderBy(x => x.Id);
                                }
                                else
                                {
                                    dset = set.OrderBy(x => x.Id).Where(exp);
                                }

                                var lst = dset.AsNoTracking()
                                    .Skip(bat * batchSize)
                                    .Take(batchSize)
                                    .ToList();
                                res.Enqueue(lst);
                            }

                        }
                        catch (Exception ex)
                        {
                            exceptions.Enqueue(ex);
                        }
                    }
                    );
                if (exceptions.Count > 0) throw new AggregateException(exceptions);
    
                var entities = res.SelectMany(x => x.ToList());
                if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                return Task.FromResult(entities); 

            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                var fault = new ValidationFault
                {
                    Result = false,
                    Message = updateEx.Message,
                    Description = updateEx.StackTrace
                };
                throw new FaultException<ValidationFault>(fault);
            }
        }
        public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByBatchExpressionLst(List<string> expLst,
                                                                                         int totalrow, List<string> includesLst = null, bool tracking = true)
        {
            try
            {

                var res = new ConcurrentQueue<List<ShipmentRiderEx>>();



                if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return Task.FromResult<IEnumerable<ShipmentRiderEx>>(new List<ShipmentRiderEx>());


                var batchSize = 500;
                var batches = Convert.ToInt32(totalrow / batchSize);

                if (totalrow % batchSize > 0) batches += 1;
                var exceptions = new ConcurrentQueue<Exception>();
                Parallel.For(0, batches,
                   new ParallelOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount * 2 },
                    bat =>
                    //  for (int bat = 0; bat < batches; bat++)
                    {
                        try
                        {
                            using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                            {
                                dbContext.Database.CommandTimeout = 0;
                                dbContext.Configuration.AutoDetectChangesEnabled = false;
                                //dbContext.Configuration.LazyLoadingEnabled = true;
                                var set = AddIncludes(includesLst, dbContext);
                                IQueryable<ShipmentRiderEx> dset;
                                if (expLst.FirstOrDefault() == "All")
                                {
                                    dset = set.OrderBy(x => x.Id);
                                }
                                else
                                {
                                    set = AddWheres(expLst, set);
                                    dset = set.OrderBy(x => x.Id);
                                }

                                var lst = dset.AsNoTracking()
                                    .Skip(bat * batchSize)
                                    .Take(batchSize)
                                    .ToList();
                                res.Enqueue(lst);
                            }

                        }
                        catch (Exception ex)
                        {
                            exceptions.Enqueue(ex);
                        }
                    }
                    );
                if (exceptions.Count > 0) throw new AggregateException(exceptions);
                var entities = res.SelectMany(x => x.ToList());
                if(tracking) entities.AsParallel(new ParallelLinqOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount }).ForAll(x => x.StartTracking());
                return Task.FromResult(entities); 
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                var fault = new ValidationFault
                {
                    Result = false,
                    Message = updateEx.Message,
                    Description = updateEx.StackTrace
                };
                throw new FaultException<ValidationFault>(fault);
            }
        }


        public Task<ShipmentRiderEx> UpdateShipmentRiderEx(ShipmentRiderEx entity)
        { 
            using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
              {
                try
                {   
                     var res = (ShipmentRiderEx) entity;
                    if(res.TrackingState == TrackingState.Unchanged) res.TrackingState = TrackingState.Modified;                              
                    
                    dbContext.ApplyChanges(res);
                    dbContext.SaveChanges();
                    res.AcceptChanges();
                    return Task.FromResult(res);      
      
                }
                catch (DbUpdateConcurrencyException dce)
                {
                    // Get failed entry
                    foreach (var itm in dce.Entries)
                    {
                        if(itm.State != EntityState.Added)
                         {
                            var dv = itm.GetDatabaseValues();
                            if(dv != null) itm.OriginalValues.SetValues(dv);
                        }
                    }
                }
                catch (OptimisticConcurrencyException oce)
                {
                    var context = ((IObjectContextAdapter)dbContext).ObjectContext;

                    foreach (var entry in oce.StateEntries)
                    {
                        context.Refresh(System.Data.Entity.Core.Objects.RefreshMode.StoreWins, entry.Entity);
                    }
                }   
                catch (DbUpdateException e)
                {
                    
                   // Debugger.Break();
                    SqlException s = e.InnerException.InnerException as SqlException;
                    if (s != null && s.Number == 2627)
                    {
                         
                    }
                    else
                    {
                        Debugger.Break();
                        throw;
                    }
                }             
                catch (Exception updateEx)
                {
                    if (
                        updateEx.Message.Contains(
                            "The changes to the database were committed successfully, " +
                            "but an error occurred while updating the object context"))
                        return Task.FromResult(entity);

                    System.Diagnostics.Debugger.Break();
                    //throw new FaultException(updateEx.Message);
                        var fault = new ValidationFault
                                    {
                                        Result = false,
                                        Message = updateEx.Message,
                                        Description = updateEx.StackTrace
                                    };
                        throw new FaultException<ValidationFault>(fault);
                }
            }
           return Task.FromResult(entity);
        }

        public Task<ShipmentRiderEx> CreateShipmentRiderEx(ShipmentRiderEx entity)
        {
            try
            {
                var res = (ShipmentRiderEx) entity;
              using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
              {
                dbContext.ShipmentRiderEx.Add(res);
                dbContext.SaveChanges();
                res.AcceptChanges();
                return Task.FromResult(res);
              }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

        public Task<bool> DeleteShipmentRiderEx(string Id)
        {
            try
            {
              using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
              {
                var i = Convert.ToInt32(Id);
                ShipmentRiderEx entity = dbContext.ShipmentRiderEx
													.SingleOrDefault(x => x.Id == i);
                if (entity == null)
                    return Task.FromResult(false);

                    dbContext.ShipmentRiderEx.Attach(entity);
                    dbContext.ShipmentRiderEx.Remove(entity);
                    dbContext.SaveChanges();
                    return Task.FromResult(true);
              }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

        public async Task<bool> RemoveSelectedShipmentRiderEx(IEnumerable<string> lst)
        {
            try
            {
                StatusModel.StartStatusUpdate("Removing ShipmentRiderEx", lst.Count());
                var t = Task.Run(() =>
                {
                    using (var ctx = new ShipmentRiderExService())
                    {
                        foreach (var item in lst.ToList())
                        {

                            ctx.DeleteShipmentRiderEx(item).Wait();
                            StatusModel.StatusUpdate();
                        }
                    }
                });
                await t.ConfigureAwait(false);
                return true;
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
            

               
        }

		// Virtural list Implementation

         public Task<int> CountByExpressionLst(List<string> expLst)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if (expLst.Count == 0 || expLst.FirstOrDefault() == "None") return Task.FromResult(0);
                    var set = (IQueryable<ShipmentRiderEx>)dbContext.ShipmentRiderEx; 
                    if (expLst.FirstOrDefault() == "All")
                    {
                        return Task.FromResult(set.AsNoTracking().Count());
                    }
                    else
                    {
                        set = AddWheres(expLst, set);
                        return Task.FromResult(set.AsNoTracking().Count());
                    }
                    
                }
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                var fault = new ValidationFault
                {
                    Result = false,
                    Message = updateEx.Message,
                    Description = updateEx.StackTrace
                };
                throw new FaultException<ValidationFault>(fault);
            }
        }

		public Task<int> Count(string exp)
        {
            try
            {
                using (EntryDataDSContext dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    if (string.IsNullOrEmpty(exp) || exp == "None") return Task.FromResult(0);
                    if (exp == "All")
                    {
                        return Task.FromResult(dbContext.ShipmentRiderEx
                            .AsNoTracking()
                            .Count());
                    }
                    else
                    {
                        
                        return Task.FromResult(dbContext.ShipmentRiderEx
                            .AsNoTracking()
                            .Where(exp)
                            .Count());
                    }
                }
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }
        
        public Task<IEnumerable<ShipmentRiderEx>> LoadRange(int startIndex, int count, string exp)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if (string.IsNullOrEmpty(exp) || exp == "None") return Task.FromResult<IEnumerable<ShipmentRiderEx>>(new List<ShipmentRiderEx>());
                    if (exp == "All")
                    {
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(dbContext.ShipmentRiderEx
                            .AsNoTracking()
                            .OrderBy(y => y.Id)
                            .Skip(startIndex)
                            .Take(count)
                            .ToList());
                    }
                    else
                    {
                        
                        return Task.FromResult<IEnumerable<ShipmentRiderEx>>(dbContext.ShipmentRiderEx
                            .AsNoTracking()
                            .Where(exp)
                            .OrderBy(y => y.Id)
                            .Skip(startIndex)
                            .Take(count)
                            .ToList());
                    }
                }
            }
            catch (Exception updateEx)
            {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

		public async Task<int> CountNav(string exp, Dictionary<string, string> navExp)
        {
            try
            {
                if (string.IsNullOrEmpty(exp) || exp == "None") return 0;
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if (exp == "All" && navExp.Count == 0)
                    {
                        return dbContext.ShipmentRiderEx
										.AsNoTracking()
                                        .Count();
                    }
                    foreach (var itm in navExp)
                    {
                        switch (itm.Key)
                        {
                            case "ShipmentRider":
                                return await CountWhere<ShipmentRider>(dbContext, exp, itm.Value, "ShipmentRiderEx", "SelectMany")
											.ConfigureAwait(continueOnCapturedContext: false);
						}
                    }
                    return dbContext.ShipmentRiderEx.Where(exp == "All" || exp == null ? "Id != null" : exp)
											.AsNoTracking()
                                            .Count();
                }
                
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                var fault = new ValidationFault
                {
                    Result = false,
                    Message = updateEx.Message,
                    Description = updateEx.StackTrace
                };
                throw new FaultException<ValidationFault>(fault);
            }
        }

		private static async Task<int> CountWhere<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp, string rel) where T : class
        {
              switch (rel)
		    {
		        case "SelectMany":
                    return await CountWhereSelectMany<T>(dbContext, exp, navExp, navProp)
									.ConfigureAwait(continueOnCapturedContext: false);
		            
                default:
                    return await CountWhereSelect<T>(dbContext, exp, navExp, navProp)
									.ConfigureAwait(continueOnCapturedContext: false);
		    }
        }

		private static Task<int> CountWhereSelectMany<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp) where T : class
        {
			try
			{
            return Task.FromResult(dbContext.Set<T>()
                .AsNoTracking()
                .Where(navExp)
                .SelectMany(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null ? "Id != null" : exp)
                .Distinct()
                .OrderBy("Id")
                .Count());
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		private static Task<int> CountWhereSelect<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp) where T : class
        {
			try
			{
            return Task.FromResult(dbContext.Set<T>()
                .AsNoTracking()
                .Where(navExp)
                .Select(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null ? "Id != null" : exp)
                .Distinct()
                .OrderBy("Id")
                .Count());
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		  public async Task<IEnumerable<ShipmentRiderEx>> LoadRangeNav(int startIndex, int count, string exp,
                                                                                 Dictionary<string, string> navExp, IEnumerable<string> includeLst = null)
        {
            try
            {
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if ((string.IsNullOrEmpty(exp) && navExp.Count == 0) || exp == "None") return new List<ShipmentRiderEx>();
                    var set = AddIncludes(includeLst, dbContext);

                    if (exp == "All" && navExp.Count == 0)
                    {
                       
                        return set
									.AsNoTracking()
                                    .OrderBy(y => y.Id)
 
                                    .Skip(startIndex)
                                    .Take(count)
									.ToList();
                    }
                    foreach (var itm in navExp)
                    {
                        switch (itm.Key)
                        {
                            case "ShipmentRider":
                                return
                                    await
                                        LoadRangeWhere<ShipmentRider>(startIndex, count, dbContext, exp, itm.Value, "ShipmentRiderEx", "SelectMany")
													.ConfigureAwait(continueOnCapturedContext: false);

                          
							default:
                                throw new ArgumentException("No Navigation property found for " + itm.Key);
						}

                    }
                    return set//dbContext.ShipmentRiderEx
								.AsNoTracking()
                                .Where(exp == "All" || exp == null ? "Id != null" : exp)
								.OrderBy(y => y.Id)
 
                                .Skip(startIndex)
                                .Take(count)
								.ToList();


                }
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }

		private static async Task<IEnumerable<ShipmentRiderEx>> LoadRangeWhere<T>(int startIndex, int count,
            EntryDataDSContext dbContext, string exp, string navExp, string navProp, string rel, IEnumerable<string> includeLst = null) where T : class
        {
             switch (rel)
		    {
		        case "SelectMany":
                    return await LoadRangeSelectMany<T>(startIndex, count, dbContext, exp, navExp, navProp, includeLst)
									.ConfigureAwait(continueOnCapturedContext: false);
		            
                default:
                    return await LoadRangeSelect<T>(startIndex, count, dbContext, exp, navExp, navProp, includeLst)
									.ConfigureAwait(continueOnCapturedContext: false);
		    }
        }

		private static Task<IEnumerable<ShipmentRiderEx>> LoadRangeSelectMany<T>(int startIndex, int count,
                                                                                 EntryDataDSContext dbContext, string exp, string navExp, string navProp, IEnumerable<string> includeLst = null) where T : class
        {
			try
			{
            var set = dbContext.Set<T>()
				.AsNoTracking()
                .Where(navExp)
                .SelectMany(navProp).OfType<ShipmentRiderEx>();
    
            if (includeLst != null) set = includeLst.Aggregate(set, (current, itm) => current.Include(itm));            

            return Task.FromResult<IEnumerable<ShipmentRiderEx>>(set
                .Where(exp == "All" || exp == null ? "Id != null" : exp)
                .Distinct()
                .OrderBy(y => y.Id)
 
                .Skip(startIndex)
                .Take(count)
                .ToList());
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		private static Task<IEnumerable<ShipmentRiderEx>> LoadRangeSelect<T>(int startIndex, int count,
                                                                             EntryDataDSContext dbContext, string exp, string navExp, string navProp, IEnumerable<string> includeLst = null) where T : class
        {
			try
			{
              var set = dbContext.Set<T>()
				.AsNoTracking()
                .Where(navExp)
                .Select(navProp).OfType<ShipmentRiderEx>();

               if (includeLst != null) set = includeLst.Aggregate(set, (current, itm) => current.Include(itm)); 
                
               return Task.FromResult<IEnumerable<ShipmentRiderEx>>(set
                   .Where(exp == "All" || exp == null ? "Id != null" : exp)
                   .Distinct()
                   .OrderBy(y => y.Id)
 
                   .Skip(startIndex)
                   .Take(count)
                   .ToList());
							 }
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

        private static async Task<IEnumerable<ShipmentRiderEx>> GetWhere<T>(EntryDataDSContext dbContext,
            string exp, string navExp, string navProp, string rel, List<string> includesLst = null) where T : class
        {
			try
			{
			    switch (rel)
				{
					case "SelectMany":
						return await GetWhereSelectMany<T>(dbContext, exp, navExp, navProp, includesLst)
										.ConfigureAwait(continueOnCapturedContext: false);
						
					default:
						return await GetWhereSelect<T>(dbContext, exp, navExp, navProp, includesLst)
										.ConfigureAwait(continueOnCapturedContext: false);
				}
			
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		private static Task<IEnumerable<ShipmentRiderEx>> GetWhereSelectMany<T>(EntryDataDSContext dbContext,
                                                                                string exp, string navExp, string navProp, List<string> includesLst = null) where T : class
        {
			try
			{

			if (includesLst == null)
			{
				return Task.FromResult<IEnumerable<ShipmentRiderEx>>(dbContext.Set<T>()
                    .AsNoTracking()
                    .Where(navExp)
                    .SelectMany(navProp).OfType<ShipmentRiderEx>()
                    .Where(exp == "All" || exp == null?"Id != null":exp)
                    .Distinct()
                    .ToList());
			}

			var set = (DbQuery<ShipmentRiderEx>)dbContext.Set<T>()
				.AsNoTracking()
                .Where(navExp)
                .SelectMany(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null?"Id != null":exp)
                .Distinct();

			set = includesLst.Aggregate(set, (current, itm) => current.Include(itm));

            return Task.FromResult<IEnumerable<ShipmentRiderEx>>(set.ToList());
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		private static Task<IEnumerable<ShipmentRiderEx>> GetWhereSelect<T>(EntryDataDSContext dbContext,
                                                                            string exp, string navExp, string navProp, List<string> includesLst = null) where T : class
        {
			try
			{

			if (includesLst == null)
			{
				return Task.FromResult<IEnumerable<ShipmentRiderEx>>(dbContext.Set<T>()
                    .AsNoTracking()
                    .Where(navExp)
                    .Select(navProp).OfType<ShipmentRiderEx>()
                    .Where(exp == "All" || exp == null?"Id != null":exp)
                    .Distinct()
                    .ToList());
			}

			var set = (DbQuery<ShipmentRiderEx>)dbContext.Set<T>()
				.AsNoTracking()
                .Where(navExp)
                .Select(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null?"Id != null":exp)
                .Distinct();

			set = includesLst.Aggregate(set, (current, itm) => current.Include(itm));

            return Task.FromResult<IEnumerable<ShipmentRiderEx>>(set.ToList());
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

			        public Task<IEnumerable<ShipmentRiderEx>> GetShipmentRiderExByApplicationSettingsId(string ApplicationSettingsId, List<string> includesLst = null)
        {
            try
            {
                using ( var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
              {
                var i = Convert.ToInt32(ApplicationSettingsId);
                var set = AddIncludes(includesLst, dbContext);
                IEnumerable<ShipmentRiderEx> entities = set//dbContext.ShipmentRiderEx
                                      .AsNoTracking()
                                        .Where(x => x.ApplicationSettingsId.ToString() == ApplicationSettingsId.ToString())
										.ToList();
                return Task.FromResult(entities);
              }
             }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }
        }
 
		public decimal SumField(string whereExp, string field)
         {
             try
             {
                 using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                 {
                    dbContext.Database.CommandTimeout = 0;
					decimal res = 0;
                     if (string.IsNullOrEmpty(whereExp) || whereExp == "None") return 0;
                     if (whereExp == "All")
                     {
                          res = Convert.ToDecimal(dbContext.ShipmentRiderEx.AsNoTracking().Sum(field));
                     }
                     else
                     {
                         res = Convert.ToDecimal(dbContext.ShipmentRiderEx.AsNoTracking().Where(whereExp).Sum(field));
                     }
                     
                     return res;
                 }
             }
             catch (Exception updateEx)
             {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
             }
         }

        public async Task<decimal> SumNav( string exp, Dictionary<string, string> navExp, string field)
        {
            try
            {
                if (string.IsNullOrEmpty(exp) || exp == "None") return 0;
                using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                {
                    dbContext.Database.CommandTimeout = 0;
                    if (!dbContext.ShipmentRiderEx.Any()) return 0;
                    if (exp == "All" && navExp.Count == 0)
                    {
                        return Convert.ToDecimal(dbContext.ShipmentRiderEx
										.AsNoTracking()
                                        .Sum(field)??0);
                    }
                    foreach (var itm in navExp)
                    {
                        switch (itm.Key)
                        {
                            case "ShipmentRider":
                                return await SumWhere<ShipmentRider>(dbContext, exp, itm.Value, "ShipmentRiderEx", field, "SelectMany")
											.ConfigureAwait(continueOnCapturedContext: false);
						}
                    }
                    return Convert.ToDecimal(dbContext.ShipmentRiderEx.Where(exp == "All" || exp == null ? "Id != null" : exp)
											.AsNoTracking()
                                            .Sum(field)??0);
                }
                
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                var fault = new ValidationFault
                {
                    Result = false,
                    Message = updateEx.Message,
                    Description = updateEx.StackTrace
                };
                throw new FaultException<ValidationFault>(fault);
            }
        }

		private static async Task<decimal> SumWhere<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp, string field, string rel) where T : class
        {
              switch (rel)
		    {
		        case "SelectMany":
                    return await SumWhereSelectMany<T>(dbContext, exp, navExp, navProp, field)
									.ConfigureAwait(continueOnCapturedContext: false);
		        default:
                    return await SumWhereSelect<T>(dbContext, exp, navExp, navProp, field)
									.ConfigureAwait(continueOnCapturedContext: false);
		    }
        }

		private static Task<decimal> SumWhereSelectMany<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp, string field) where T : class
        {
			try
			{
            return Task.FromResult(Convert.ToDecimal(dbContext.Set<T>()
                .AsNoTracking()
                .Where(navExp)
                .SelectMany(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null ? "Id != null" : exp)
                .Distinct()
                .OrderBy("Id")
                .Sum(field)));
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }

		private static Task<decimal> SumWhereSelect<T>(EntryDataDSContext dbContext, string exp, string navExp, string navProp, string field) where T : class
        {
			try
			{
            return Task.FromResult(Convert.ToDecimal(dbContext.Set<T>()
                .AsNoTracking()
                .Where(navExp)
                .Select(navProp).OfType<ShipmentRiderEx>()
                .Where(exp == "All" || exp == null ? "Id != null" : exp)
                .Distinct()
                .OrderBy("Id")
                .Sum(field)));
			}
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
        }



		 public string MinField(string whereExp, string field)
         {
             try
             {
                 using (var dbContext = new EntryDataDSContext(){StartTracking = StartTracking})
                 {
                    dbContext.Database.CommandTimeout = 0;
					string res = "";
                     if (string.IsNullOrEmpty(whereExp) || whereExp == "None") return res;
                     if (whereExp == "All")
                     {
                          res = Convert.ToString(dbContext.ShipmentRiderEx.AsNoTracking().Min(field));
                     }
                     else
                     {
                         res = Convert.ToString(dbContext.ShipmentRiderEx.AsNoTracking().Where(whereExp).Min(field));
                     }
                     
                     return res;
                 }
             }
             catch (Exception updateEx)
             {
                    System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
             }
         }

		 
		private static IQueryable<ShipmentRiderEx> AddIncludes(IEnumerable<string> includesLst, EntryDataDSContext dbContext)
       {
		 try
			{
			   if (includesLst == null) includesLst = new List<string>();
			   var set =(DbQuery<ShipmentRiderEx>) dbContext.ShipmentRiderEx; 
			   set = includesLst.Where(x => !string.IsNullOrEmpty(x))
                                .Aggregate(set, (current, itm) => current.Include(itm));
			   return set;
			 }
			catch (Exception)
			{
				Debugger.Break();
				throw;
			}
       }
	   private IQueryable<ShipmentRiderEx> AddWheres(List<string> expLst, IQueryable<ShipmentRiderEx> set)
        {
            try
            {
                return expLst.Where(x => !string.IsNullOrEmpty(x))
                             .Aggregate(set, (current, itm) => current.Where(itm));
            }
            catch (Exception)
            {
                Debugger.Break();
                throw;
            }
          
        }

        public void Dispose()
        {
            try
            {
               // var dispose = dbContext as IDisposable;
             ////   if (dispose != null)
            //    {
           //         dbContext.Dispose();
           //     }
            }
            catch (Exception updateEx)
            {
                System.Diagnostics.Debugger.Break();
                //throw new FaultException(updateEx.Message);
                    var fault = new ValidationFault
                                {
                                    Result = false,
                                    Message = updateEx.Message,
                                    Description = updateEx.StackTrace
                                };
                    throw new FaultException<ValidationFault>(fault);
            }

        }

    }
}



